language: python
python:
  - 3.3
  - 3.4

install:
  - pip install --upgrade setuptools
  - pip install coveralls --use-mirrors
  - python setup.py develop

script:
  coverage run --source=aiohttp setup.py test
  python setup.py check -rms
after_success:
  coveralls

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0
